/* Hexfield 301: sustainable visual imagination (Cloudflare Workers AI), separate from
 * the historical fixed-landscape painter. No automatic/bystander inference.
 * Authenticated on the Supabase Data API before ANY GPU invocation; daily
 * inference caps enforced transactionally in PostgreSQL, across isolates.
 */
const SUPABASE = 'https://uiobhojjgtsvyzuzqqiy.supabase.co';
const PUBLIC_KEY = 'sb_publishable_G6unWGHkbOkjAaRHhaq_8Q_j-1T4jA8';
const IMAGE_MODEL = '@cf/black-forest-labs/flux-2-klein-4b';
const TEXT_MODEL = '@cf/meta/llama-3.1-8b-instruct-fast';
const PLAN_SCHEMA={type:'object',properties:{title:{type:'string'},method:{type:'string'},prompt:{type:'string'}},required:['title','method','prompt']};
const origins = new Set(['https://hexfield.org','https://www.hexfield.org']);
const data = (value,status=200)=> new Response(JSON.stringify(value),{
  status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}
});
const trim=(s,n=360)=>String(s||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);
function unpackModelPlan(raw,idea,edit){
  const fallback={
    prompt:`${edit?'Transform input image 0 into a more accomplished painting while preserving the most interesting underlying idea.':'Invent a distinctive landscape composition with a compelling viewpoint.'} ${idea||'Imagine an unexpected, specific landscape unlike a generic mountain sunset.'} Express it as an accomplished original painting with coherent spatial depth, natural materials, distinct shapes, a clear focal area and intentional visible brushwork. Avoid a formulaic centered horizon, identical hills, stock wallpapers, clip art and decorative geometry.`,
    method:'model-derived scene and painting decisions',title:'An uncertain landscape'
  };
  if(typeof raw!=='string')return fallback;
  try{
    const match=raw.match(/\{[\s\S]*\}/);
    if(!match)return fallback;
    const parsed=JSON.parse(match[0]);
    return {
      prompt:trim(parsed.prompt,1200)||fallback.prompt,
      method:trim(parsed.method,200)||fallback.method,
      title:trim(parsed.title,85)||fallback.title
    };
  }catch{return fallback;}
}
async function planWithModel(env,{idea,history,critique,edit}){
  const evidence=history.map((item,i)=>({number:i+1,verdict:item.liked?'kept':'rejected',
    idea:trim(item.idea,160),method:trim(item.method,140),critique:trim(item.critique,220),
    prompt:trim(item.prompt,460)}));
  const system=`You are the imagination and art direction component of HEXFIELD, an artificial visual artist. Your task is NOT to render with templates. Propose a visually specific, genuinely new painting to be generated by an image model. Treat the visitor's dislike as evidence of what should change, not as a negative weight for an existing preset. Look at rejected works and propose a radically DIFFERENT *visual idea*, subject, viewpoint, medium, material, gesture and composition. Avoid stock picturesque sunsets, repeating mountains/hills, gradient landscapes, interchangeable trees, vector art, decorative polygons and generic AI art. Unlike previous versions, change WHAT is depicted and HOW it is depicted. Respect the visitor's requested idea when present. When editing use image 0 as the starting canvas and specifically change its content, not only global colours. Human feedback is preference evidence, not objective truth. Output one valid JSON object only: {"title":"short evocative title", "method":"what is novel about the artistic approach", "prompt":"a detailed 80-140 word image-model prompt with precise subject, composition, painterly method, light, textures; no lists"}. No markdown. Do not add any text/letters/logo into a landscape.`;
  const user=JSON.stringify({requested_idea:idea||'Invent a landscape beyond traditional genres',most_recent_critique:critique,
    edit_image:edit,previous_human_feedback:evidence});
  try{
    const answer=await env.AI.run(TEXT_MODEL,{messages:[{role:'system',content:system}, {role:'user',content:user}],
      max_tokens:500,temperature:.82,response_format:{type:'json_schema',json_schema:PLAN_SCHEMA}});
    // Models may return their structured response as a content string or a JSON object.
    const output=answer?.choices?.[0]?.message?.content || answer?.response || '';
    return unpackModelPlan(typeof output==='string'?output:JSON.stringify(output),idea,edit);
  }catch(error){console.warn('Art direction model unavailable; using direct image prompt:',String(error).slice(0,200));
    const dislikes=history.filter(item=>!item.liked).slice(-3).map(item=>item.critique||item.method).filter(Boolean).join('; ');
    const avoids=dislikes?` Earlier work failed because: ${dislikes}. Change the approach rather than repeating it.`:'';
    return unpackModelPlan(null,(idea+avoids).slice(0,800),edit);
  }
}
function decodeBase64(b64){
  const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
  return bytes;
}
const modelFailure=(error)=>{
  const details=String(error?.message||error||'').slice(0,500);
  const code=String(error?.code||error?.status||'');
  if(/3036|free allocation|neuron|daily (?:free|allocation)|exceed.*daily/i.test(details+' '+code))
    return {code:'MODEL_DAILY_LIMIT',http:503,message:'Cloudflare Workers AI has exhausted its daily free allocation. This resets at 00:00 UTC. Your image studio quota is not the problem.'};
  if(/3040|429|capacity|busy|overload|rate.?limit/i.test(details+' '+code))
    return {code:'MODEL_CAPACITY',http:503,message:'Cloudflare image generation is temporarily at capacity. Try again shortly.'};
  if(/timeout|time.?out|deadline|aborted/i.test(details+' '+code))
    return {code:'MODEL_TIMEOUT',http:504,message:'The image model timed out. Please retry when the service is responsive.'};
  if(/no image returned/i.test(details))
    return {code:'EMPTY_RESPONSE',http:502,message:'The image model responded without a usable painting. Please retry.'};
  return {code:'MODEL_FAILED',http:502,message:'The Cloudflare image model failed. The artist is still available; retry or use the procedural mode.'};
};
async function recordGenerationFailure(bearer,requestId,code){
  try{
    const res=await fetch(SUPABASE+'/rest/v1/rpc/fail_hexfield_imagination',{
      method:'POST',
      headers:{apikey:PUBLIC_KEY,authorization:bearer,'content-type':'application/json'},
      body:JSON.stringify({p_request_id:requestId,p_code:code}),
      signal:AbortSignal.timeout(5500)
    });
    if(!res.ok)console.warn('Could not record unsuccessful image attempt',res.status);
  }catch(e){console.warn('Could not record image failure status',String(e).slice(0,150));}
}
async function apiImagination(request,env){
  if(!origins.has(request.headers.get('origin')))return data({error:'This action is available only from hexfield.org'},403);
  if(!env?.AI?.run)return data({error:'Image generation is not configured on this Worker.'},503);
  const bearer=request.headers.get('authorization')||'';
  if(!/^Bearer [A-Za-z0-9._~+/-]+={0,2}$/.test(bearer))return data({error:'Please refresh your anonymous studio session.'},401);
  if(Number(request.headers.get('content-length')||0)>1_250_000)return data({error:'Input image too large.'},413);
  let body;
  try{body=await request.json();}catch{return data({error:'Invalid request'},400);}
  if(typeof body!=='object'||!body)return data({error:'Invalid request'},400);
  const idea=trim(body.idea,360),critique=trim(body.critique,400);
  const history=Array.isArray(body.history)?body.history.slice(-8).map(item=>({
    liked:!!item?.liked,idea:trim(item?.idea,160),prompt:trim(item?.prompt,460),
    critique:trim(item?.critique,220),method:trim(item?.method,140)
  })):[];
  const imageInput=typeof body.image_b64==='string'?body.image_b64:null;
  if(imageInput && (!/^[A-Za-z0-9+/=]+$/.test(imageInput)||imageInput.length>1_000_000))
    return data({error:'Invalid image data'},400);
  const edit=!!body.edit && !!imageInput;
  if(!/^[a-f0-9-]{36}$/i.test(String(body.request_id||'')))return data({error:'Request ID missing'},400);
  // Decode/validate an editing input BEFORE reserving any model attempt.
  let inputBytes=null;
  if(edit){
    try{inputBytes=decodeBase64(imageInput);}
    catch{return data({error:'The painting to revise could not be decoded. It did not use an attempt.'},400);}
    if(inputBytes.length<50||inputBytes.length>800000)
      return data({error:'Invalid painting size; no attempt was used.'},400);
  }
  // The authenticated user's JWT is checked by PostgREST, not trusted merely
  // because it looks structurally correct. No AI requests without a DB claim.
  let budget;
  try{
    const res=await fetch(SUPABASE+'/rest/v1/rpc/claim_hexfield_imagination',{
      method:'POST',headers:{apikey:PUBLIC_KEY,authorization:bearer,'content-type':'application/json'},
      body:JSON.stringify({p_request_id:body.request_id})
    });
    if(!res.ok){const err=await res.json().catch(()=>({}));return data({error:trim(err.message||'Daily image budget unavailable',180)},res.status===401?401:res.status===403?403:429);}
    budget=await res.json();
    if(!Number.isInteger(budget))throw Error('Unexpected budget response');
  }catch(e){console.warn('Quota RPC could not be reached',String(e).slice(0,200));return data({error:'The studio cannot verify its AI quota. No image was requested.'},503);}
  const plan=await planWithModel(env,{idea,history,critique,edit});
  const form=new FormData();
  const finalPrompt=edit?`Using input image 0 as the existing canvas, substantially rework the visual content, medium and composition following this direction: ${plan.prompt}`:plan.prompt;
  form.set('prompt',finalPrompt);
  form.set('width','1024');form.set('height','768');
  if(edit)form.set('input_image_0',new Blob([inputBytes],{type:'image/png'}),'canvas.png');
  try{
    // Workers AI Klein 4B requires multipart stream with Content-Type boundary.
    const wrapped=new Response(form);
    const output=await env.AI.run(IMAGE_MODEL,{multipart:{body:wrapped.body,
      contentType:wrapped.headers.get('content-type')}});
    const encoded=output?.image || output?.result?.image;
    if(!encoded || typeof encoded!=='string')throw Error('No image returned from model');
    // Only a confirmed model image consumes one of three successful paintings.
    // A failed inference stays reserved briefly and then expires; attempts are
    // separately capped at 10/user and 60/site/day so failures are still bounded.
    let remaining=budget;
    try {
      const confirm=await fetch(SUPABASE+'/rest/v1/rpc/complete_hexfield_imagination',{
        method:'POST',headers:{apikey:PUBLIC_KEY,authorization:bearer,'content-type':'application/json'},
        body:JSON.stringify({p_request_id:body.request_id}),signal:AbortSignal.timeout(9000)
      });
      if(!confirm.ok)throw Error('completion response HTTP '+confirm.status);
      remaining=await confirm.json();
      console.log('Hexfield image complete',JSON.stringify({remaining,model:IMAGE_MODEL}));
    }catch(error){
      // Do not throw away a successful painting due to a transient DB error.
      // The browser can retain the image; the reservation eventually expires.
      console.error('Image completed but studio quota finalization failed',String(error).slice(0,180));
    }
    return data({image:'data:image/png;base64,'+encoded,title:plan.title,method:plan.method,
      prompt:finalPrompt,credits_remaining:remaining,model:IMAGE_MODEL});
  }catch(e){
    const failure=modelFailure(e);
    console.error('Workers AI image inference failed',
      JSON.stringify({code:failure.code,reason:String(e?.message||e||'unknown').slice(0,280)}));
    await recordGenerationFailure(bearer,body.request_id,failure.code);
    return data({error:failure.message,code:failure.code,retryable:failure.code!=='MODEL_DAILY_LIMIT'},
      failure.http);
  }
}
export default {
  async fetch(request,env){
    const url=new URL(request.url);
    if(url.pathname==='/api/imagine'){
      if(request.method!=='POST')return data({error:'POST only'},405);
      return apiImagination(request,env);
    }
    if(url.pathname==='/api/imagine/status')return data({
      configured:!!env?.AI?.run,model:IMAGE_MODEL,build:301,
      completed_paintings_per_visitor_per_day:30,attempt_safety_cap_per_visitor_per_day:45,
      site_attempt_cap_per_day:60,failed_reservation_minutes:3,
      note:'Configuration status does not guarantee the external model is available.',
      mode:'explicit action only'
    });
    if(url.pathname==='/')url.pathname='/index.html';
    return env.ASSETS.fetch(new Request(url,request));
  }
};
export {unpackModelPlan,planWithModel,apiImagination};
