/* Hexfield 299: real visual imagination (Cloudflare Workers AI), separate from
 * the historical fixed-landscape painter. No automatic/bystander inference.
 * Authenticated on the Supabase Data API before ANY GPU invocation; daily
 * inference caps enforced transactionally in PostgreSQL, across isolates.
 */
const SUPABASE = 'https://uiobhojjgtsvyzuzqqiy.supabase.co';
const PUBLIC_KEY = 'sb_publishable_G6unWGHkbOkjAaRHhaq_8Q_j-1T4jA8';
const IMAGE_MODEL = '@cf/black-forest-labs/flux-2-klein-4b';
const TEXT_MODEL = '@cf/meta/llama-3.1-8b-instruct-fast';
const origins = new Set(['https://hexfield.org','https://www.hexfield.org']);
const data = (value,status=200)=> new Response(JSON.stringify(value),{
  status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}
});
const trim=(s,n=360)=>String(s||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);
function unpackModelPlan(raw,idea,edit){
  const fallback={
    prompt:`${edit?'Transform input image 0 into a more accomplished painting while preserving the most interesting underlying idea.':'Invent a distinctive landscape composition with a compelling viewpoint.'} ${idea||'Imagine an unexpected, specific landscape unlike a generic mountain sunset.'} Express it as an accomplished original painting with coherent spatial depth, natural materials, distinct shapes, a clear focal area and intentional visible brushwork. Avoid a formulaic centered horizon, identical hills, stock wallpapers, clip art and decorative geometry.`,
    method:'model-derived scene and painting decisions',title:'An uncertain landscape'
  };
  if(typeof raw!=='string')return fallback;
  try{
    const match=raw.match(/\{[\s\S]*\}/);
    if(!match)return fallback;
    const parsed=JSON.parse(match[0]);
    return {
      prompt:trim(parsed.prompt,1200)||fallback.prompt,
      method:trim(parsed.method,200)||fallback.method,
      title:trim(parsed.title,85)||fallback.title
    };
  }catch{return fallback;}
}
async function planWithModel(env,{idea,history,critique,edit}){
  const evidence=history.map((item,i)=>({number:i+1,verdict:item.liked?'kept':'rejected',
    idea:trim(item.idea,160),method:trim(item.method,140),critique:trim(item.critique,220),
    prompt:trim(item.prompt,460)}));
  const system=`You are the imagination and art direction component of HEXFIELD, an artificial visual artist. Your task is NOT to render with templates. Propose a visually specific, genuinely new painting to be generated by an image model. Treat the visitor's dislike as evidence of what should change, not as a negative weight for an existing preset. Look at rejected works and propose a radically DIFFERENT *visual idea*, subject, viewpoint, medium, material, gesture and composition. Avoid stock picturesque sunsets, repeating mountains/hills, gradient landscapes, interchangeable trees, vector art, decorative polygons and generic AI art. Unlike previous versions, change WHAT is depicted and HOW it is depicted. Respect the visitor's requested idea when present. When editing use image 0 as the starting canvas and specifically change its content, not only global colours. Human feedback is preference evidence, not objective truth. Output one valid JSON object only: {"title":"short evocative title", "method":"what is novel about the artistic approach", "prompt":"a detailed 80-140 word image-model prompt with precise subject, composition, painterly method, light, textures; no lists"}. No markdown. Do not add any text/letters/logo into a landscape.`;
  const user=JSON.stringify({requested_idea:idea||'Invent a landscape beyond traditional genres',most_recent_critique:critique,
    edit_image:edit,previous_human_feedback:evidence});
  try{
    const answer=await env.AI.run(TEXT_MODEL,{messages:[{role:'system',content:system}, {role:'user',content:user}],max_tokens:450,temperature:.94});
    const text=answer?.response || answer?.choices?.[0]?.message?.content || '';
    return unpackModelPlan(text,idea,edit);
  }catch(error){console.warn('Art direction model unavailable; using direct image prompt:',String(error).slice(0,200));
    const dislikes=history.filter(item=>!item.liked).slice(-3).map(item=>item.critique||item.method).filter(Boolean).join('; ');
    const avoids=dislikes?` Earlier work failed because: ${dislikes}. Change the approach rather than repeating it.`:'';
    return unpackModelPlan(null,(idea+avoids).slice(0,800),edit);
  }
}
function decodeBase64(b64){
  const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
  return bytes;
}
async function apiImagination(request,env){
  if(!origins.has(request.headers.get('origin')))return data({error:'This action is available only from hexfield.org'},403);
  if(!env?.AI?.run)return data({error:'Image generation is not configured on this Worker.'},503);
  const bearer=request.headers.get('authorization')||'';
  if(!/^Bearer [A-Za-z0-9._~+/-]+={0,2}$/.test(bearer))return data({error:'Please refresh your anonymous studio session.'},401);
  if(Number(request.headers.get('content-length')||0)>1_250_000)return data({error:'Input image too large.'},413);
  let body;
  try{body=await request.json();}catch{return data({error:'Invalid request'},400);}
  if(typeof body!=='object'||!body)return data({error:'Invalid request'},400);
  const idea=trim(body.idea,360),critique=trim(body.critique,400);
  const history=Array.isArray(body.history)?body.history.slice(-8).map(item=>({
    liked:!!item?.liked,idea:trim(item?.idea,160),prompt:trim(item?.prompt,460),
    critique:trim(item?.critique,220),method:trim(item?.method,140)
  })):[];
  const imageInput=typeof body.image_b64==='string'?body.image_b64:null;
  if(imageInput && (!/^[A-Za-z0-9+/=]+$/.test(imageInput)||imageInput.length>1_000_000))
    return data({error:'Invalid image data'},400);
  const edit=!!body.edit && !!imageInput;
  if(!/^[a-f0-9-]{36}$/i.test(String(body.request_id||'')))return data({error:'Request ID missing'},400);
  // The authenticated user's JWT is checked by PostgREST, not trusted merely
  // because it looks structurally correct. No AI requests without a DB claim.
  let budget;
  try{
    const res=await fetch(SUPABASE+'/rest/v1/rpc/claim_hexfield_imagination',{
      method:'POST',headers:{apikey:PUBLIC_KEY,authorization:bearer,'content-type':'application/json'},
      body:JSON.stringify({p_request_id:body.request_id})
    });
    if(!res.ok){const err=await res.json().catch(()=>({}));return data({error:trim(err.message||'Daily image budget unavailable',180)},res.status===401?401:res.status===403?403:429);}
    budget=await res.json();
    if(!Number.isInteger(budget))throw Error('Unexpected budget response');
  }catch(e){console.warn('Quota RPC could not be reached',String(e).slice(0,200));return data({error:'The studio cannot verify its AI quota. No image was requested.'},503);}
  const plan=await planWithModel(env,{idea,history,critique,edit});
  const form=new FormData();
  form.set('prompt',plan.prompt);
  form.set('width','1024');form.set('height','768');
  if(edit){
    try{const bytes=decodeBase64(imageInput);form.set('input_image_0',new Blob([bytes],{type:'image/png'}),'canvas.png');}
    catch{return data({error:'Could not read the painting to revise'},400);}
  }
  try{
    // Workers AI Klein 4B requires multipart stream with Content-Type boundary.
    const wrapped=new Response(form);
    const output=await env.AI.run(IMAGE_MODEL,{multipart:{body:wrapped.body,
      contentType:wrapped.headers.get('content-type')}});
    const encoded=output?.image || output?.result?.image;
    if(!encoded || typeof encoded!=='string')throw Error('No image returned');
    return data({image:'data:image/png;base64,'+encoded,title:plan.title,method:plan.method,
      prompt:plan.prompt,credits_remaining:budget,model:IMAGE_MODEL});
  }catch(e){console.error('Workers AI image inference failed',String(e).slice(0,300));
    return data({error:'The image model failed to create a painting. The daily budget may still count this attempt.'},502);
  }
}
export default {
  async fetch(request,env){
    const url=new URL(request.url);
    if(url.pathname==='/api/imagine'){
      if(request.method!=='POST')return data({error:'POST only'},405);
      return apiImagination(request,env);
    }
    if(url.pathname==='/api/imagine/status')return data({ready:!!env?.AI?.run,model:IMAGE_MODEL,limit_per_visitor_per_day:3,site_limit_per_day:60,
      mode:'explicit action only'});
    if(url.pathname==='/')url.pathname='/index.html';
    return env.ASSETS.fetch(new Request(url,request));
  }
};
export {unpackModelPlan,planWithModel,apiImagination};
