-- Restore Hexfield's shared novelty memory and atomic simulation counters.
-- Deployed to Supabase project uiobhojjgtsvyzuzqqiy.
-- The legacy public.hexfield_signatures has a different text-based schema; leave it intact.
create table if not exists public.hexfield_render_signatures (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null default auth.uid(),
  field text not null,
  signature jsonb not null,
  created_at timestamptz not null default now(),
  constraint hexfield_render_signatures_field check (field in ('ruliad','moire','fractal','billiard','iso')),
  constraint hexfield_render_signatures_shape check (jsonb_typeof(signature) = 'array' and jsonb_array_length(signature) = 64 and pg_column_size(signature) <= 2500)
);
create index if not exists hexfield_render_signatures_recent on public.hexfield_render_signatures (created_at desc);
alter table public.hexfield_render_signatures enable row level security;
drop policy if exists hexfield_render_signatures_insert_own on public.hexfield_render_signatures;
create policy hexfield_render_signatures_insert_own on public.hexfield_render_signatures
  for insert to authenticated
  with check (visitor_id = (select auth.uid()));
revoke all on public.hexfield_render_signatures from anon;
grant insert on public.hexfield_render_signatures to authenticated;
grant usage,select on sequence public.hexfield_render_signatures_id_seq to authenticated;
-- Only the server-approved sampling RPC exposes other visitors' vectors.
create or replace function public.sample_hexfield_signatures(p_limit integer default 500)
returns table(signature jsonb)
language sql volatile security definer set search_path = ''
as $$
  with newest as (
    select id, signature from public.hexfield_render_signatures
    order by created_at desc
    limit least(250, greatest(1, coalesce(p_limit, 500) / 2))
  ), older as (
    select id, signature from public.hexfield_render_signatures
    where id not in (select id from newest)
    order by random()
    limit greatest(0, least(500, coalesce(p_limit, 500)) - (select count(*) from newest))
  )
  select n.signature from newest n
  union all
  select o.signature from older o;
$$;
revoke all on function public.sample_hexfield_signatures(integer) from public, anon;
grant execute on function public.sample_hexfield_signatures(integer) to authenticated;

-- Anonymous Auth users are authenticated to PostgREST, but should only
-- be allowed to see their own private model.
drop policy if exists read_hexfield on public.hexfield_taste_profiles;
drop policy if exists read_own_hexfield_taste_profiles on public.hexfield_taste_profiles;
create policy read_own_hexfield_taste_profiles on public.hexfield_taste_profiles
  for select to authenticated using (user_id = (select auth.uid()));

-- This SQL RPC increments the single global counter atomically, not via a
-- browser-side read/modify/write that loses updates.
create or replace function public.bump_hexfield_sim(
  p_cycles bigint default 0, p_trials bigint default 0,
  p_improvements bigint default 0, p_learning bigint default 0,
  p_best_score real default 0, p_last_field text default '',
  p_last_lever text default ''
)
returns void
language plpgsql volatile security definer set search_path = ''
as $$
begin
  if (select auth.uid()) is null then raise exception 'authentication required' using errcode = '42501'; end if;
  update public.hexfield_sim_progress
  set total_cycles = total_cycles + least(50000, greatest(0, coalesce(p_cycles,0))),
      total_trials = total_trials + least(200000, greatest(0, coalesce(p_trials,0))),
      total_improvements = total_improvements + least(50000, greatest(0, coalesce(p_improvements,0))),
      learning_events = learning_events + least(50000, greatest(0, coalesce(p_learning,0))),
      best_score = greatest(best_score, least(1, greatest(0, coalesce(p_best_score,0)))),
      updated_at = now()
  where id = true;
end;
$$;
revoke all on function public.bump_hexfield_sim(bigint,bigint,bigint,bigint,real,text,text) from public, anon;
grant execute on function public.bump_hexfield_sim(bigint,bigint,bigint,bigint,real,text,text) to authenticated;
